version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    networks:
      - air-ticket-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    environment:
      DB_HOST: db
      DB_NAME: online_air_ticket_reservation_system
      DB_USER: root
      DB_PASSWORD: mysql
    depends_on:
      - db
    command: sh -c "sleep 30s ; python manage.py runserver 0.0.0.0:8000"
    networks:
      - air-ticket-net

networks:
  air-ticket-net:
