version: '3'
services:
    flask-app:
        container_name: flask-app
        build: app
        restart: always
        ports:
            - '5000:5000'
        environment:
            MYSQL_HOST: mysql
            MYSQL_PORT: 3306
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: online_Air_Ticket_Reservation_System
        volumes:
            - ./app:/app
        networks:
            - backend
    mysql:
        container_name: mysql
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=online_Air_Ticket_Reservation_System
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend:

volumes:
    app:
    db: