version: '3.8'
services:
  localhost:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: online_air_ticket_reservation_system
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_NAME: online_air_ticket_reservation_system
      DB_USER: root
      DB_PASSWORD: mysql
    depends_on:
      - localhost
    command: python manage.py runserver 127.0.0.1:8000

volumes:
  db_data:
