version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: online_Air_Ticket_Reservation_System
  db:
    image: mysql:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: online_Air_Ticket_Reservation_System
volumes:
  db-data:
