version: '3'
services:
    flask-app:
        container_name: flask-app
        build: app
        restart: always
        command: sh -c "sleep 30s ; python3 ./main.py"
        depends_on:
            - mysql
        ports:
            - '5000:5000'

    mysql:
        build: ./db/
        restart: always
        environment:
            MYSQL_DATABASE: 'online_Air_Ticket_Reservation_System'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3306:3306'